name: Bug Report
description: Report a bug in Harpocrates cryptographic library
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in Harpocrates! We take security and reliability seriously.
        
        **Security vulnerabilities should be reported privately via GitHub Security Advisories or security@agilira.com**
        
  - type: input
    id: version
    attributes:
      label: Harpocrates Version
      description: Which version of Harpocrates are you using?
      placeholder: "v1.0.0"
    validations:
      required: true
      
  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: "go version go1.21.0 linux/amd64"
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS and version are you using?
      placeholder: "Ubuntu 22.04, macOS 14.0, Windows 11"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: "Describe what happened..."
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe what you expected..."
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Call function X with parameters Y
        2. Observe behavior Z
        3. Error occurs...
    validations:
      required: true
      
  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Minimal Go code that reproduces the issue
      render: go
      placeholder: |
        package main
        
        import "github.com/agilira/harpocrates"
        
        func main() {
            // Your minimal reproduction code here
        }
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Error Output
      description: Any error messages, logs, or stack traces
      render: text
      placeholder: "Paste error output here..."
    validations:
      required: false
      
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This is not a security vulnerability (use private reporting for those)
          required: true
        - label: I have provided a minimal reproduction case
          required: false