name: Feature Request
description: Suggest a new feature or enhancement for Harpocrates
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature for Harpocrates! We value community input.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: "I would like..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: "Alternative approaches could be..."
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or references?
      placeholder: "Additional information..."
    validations:
      required: false
      
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with Harpocrates' cryptographic focus
          required: true